import { JOBS, MATERIALS, activeOrder, jobFor, nextTask, inTolerance } from './workshop-state.js?v=004';
import { SCENE_DEFS, ROOM_SHELL, OBJECT_ART } from './scene.js?v=004';
export const STATIONS={desk:'Schreibtisch · Aufträge',storage:'Regal · Lager',lathe:'Drehbank',tools:'Werkzeugschrank',rack:'Materialständer',cart:'Werkzeugwagen',vise:'Schraubstock',measure:'Messschieber',radio:'Radio',clean:'Späneeimer & Besen',build:'Bauplan · Ausbau',cat:'Späne',drill:'Standbohrmaschine'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const num=n=>n.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
const go=(id,label)=>`<button class="shop-button subtle" data-station="${id}">${label} →</button>`;
const action=(id,label,arg='',disabled=false)=>`<button class="shop-button" data-work="${id}" data-arg="${arg}" ${disabled?'disabled':''}>${label}</button>`;
const msg=t=>`<p class="shop-note">${t}</p>`;
function instruction(w){const next=nextTask(w);return `<div class="next-step"><span>NÄCHSTER SCHRITT</span><p>${next.text}</p>${go(next.station,'Dorthin')}</div>`;}
export function renderScene(w,selected){
 const hint=nextTask(w).station;
 const deskY=w.room.layout.find(p=>p.id==='desk').y;
 const layer=p=>p.id==='measure'||p.id==='vise'?deskY+1:p.y;
 const objects=[...w.room.layout].sort((a,b)=>layer(a)-layer(b)).map(p=>`<g class="scene-object ${p.id===selected?'selected':''} ${p.id===hint?'next-object':''}" data-station="${p.id}" role="button" tabindex="0" aria-label="${esc(STATIONS[p.id])}" transform="translate(${p.x} ${p.y})"><title>${esc(STATIONS[p.id])}</title>${OBJECT_ART[p.id]}<g class="object-pin"><circle cy="18" r="10"/><text y="23" text-anchor="middle">${p.id===hint?'!':'+'}</text></g></g>`).join('');
 const extension=w.room.extension?`<g class="extension"><path d="M925 830l235-136v125l-155 90z" fill="#a3a28b" stroke="#4e604e" stroke-width="5"/><path d="M930 820l150-87m-95 128 156-89" stroke="#788474" stroke-width="2"/><text x="1015" y="842" fill="#364d3c" font-size="14" transform="rotate(-30 1015 842)">ANBAU · +10 m²</text>${w.room.drill?`<g data-station="drill" class="scene-object" role="button" tabindex="0" aria-label="Standbohrmaschine" transform="translate(1085 792)"><title>Standbohrmaschine</title><path d="M-45 0l45 23 34-21-45-23z" fill="#687e61" stroke="#2b4033" stroke-width="3"/><path d="M0 2v-125" stroke="#a8b1a4" stroke-width="13"/><path d="M-31-65l48 22 25-14-45-23z" fill="#5f7c56"/><path d="M-28-152h60v40h-60z" fill="#537a51" stroke="#2b4033" stroke-width="3"/><path d="M-17-112v39m48-56 27 22" stroke="#bec4ae" stroke-width="5"/><circle cx="60" cy="-105" r="5" fill="#273d2e"/></g>`:''}</g>`:'';
 let chips='';for(let i=0;i<w.chips*7;i++)chips+=`<rect x="${510+(i*37)%185}" y="${573+(i*17)%50}" width="5" height="2" fill="#bdc5ab"/>`;
 return `<svg class="room-svg ${w.light?'':'dimmed'} ${activeOrder(w)?.status==='machining'&&!activeOrder(w)?.paused?'machine-running':''}" viewBox="0 0 1220 940" xmlns="http://www.w3.org/2000/svg" aria-label="Isometrische Werkstatt. Die Einrichtungsgegenstände sind anklickbar.">${SCENE_DEFS}${ROOM_SHELL}<g>${chips}</g>${objects}${extension}</svg>`;
}
export function stationPanel(w,selected,tab='new'){
 const o=activeOrder(w),j=jobFor(o);let body='';
 switch(selected){
 case 'desk': {
  const tabs=[['new','Neu'],['active','In Arbeit'],['done','Abgeschlossen']];
  body=`<div class="order-tabs" role="tablist" aria-label="Aufträge">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" data-order-tab="${id}">${label}</button>`).join('')}</div>`;
  const rows=w.orders.filter(x=>tab==='new'?x.status==='new':tab==='done'?x.status==='completed':!['new','completed'].includes(x.status));
  body+=rows.length?rows.map(x=>{const job=jobFor(x);return `<article class="job-card"><span class="rubber-stamp">${tab==='done'?'ERLEDIGT':'AUFTRAG'}</span><h3>${job.name}</h3><p>${job.detail}</p><dl class="shop-facts"><div><dt>Kunde</dt><dd>${job.customer}</dd></div><div><dt>Zeichnung</dt><dd>Ø ${job.diameter} × ${job.length} mm</dd></div><div><dt>Werkstoff</dt><dd>${MATERIALS[job.material].name}</dd></div><div><dt>Vergütung</dt><dd>${euro(job.pay)}</dd></div></dl>${tab==='new'?action('accept','Auftrag annehmen',job.id,!!o):tab==='done'?msg('Geprüft, übergeben und bezahlt.'):x.status==='checked'?action('deliver','Abgeben · '+euro(job.pay)):instruction(w)}</article>`;}).join(''):msg(tab==='new'?'Alle angebotenen Testaufträge sind angenommen oder erledigt.':tab==='done'?'Hier erscheinen deine fertig abgelieferten Aufträge.':'Momentan ist kein Auftrag in Bearbeitung.');
  if(o&&tab==='new')body+=go('desk','Laufenden Auftrag ansehen');break;
 }
 case 'storage': body=msg('Rohmaterial und fertige Teile. Lieferungen kommen im Funktionstest sofort an.')+Object.entries(MATERIALS).map(([id,m])=>`<article class="stock-row"><span class="material-swatch" style="background:${m.color}"></span><div><h3>${m.name}</h3><p>${w.stock[id]} Rohlinge · ${euro(m.price)} / Stück</p></div>${action('buy-material','+3 · '+euro(m.price*3),id,w.money<m.price*3)}</article>`).join('')+`<div class="shop-divider">FERTIGE TEILE</div>`+msg(w.orders.filter(x=>['deburred','checked'].includes(x.status)).map(x=>jobFor(x).name+(x.status==='checked'?' · geprüft':' · Prüfung offen')).join('<br>')||'Noch keine fertigen Teile im Lager.');break;
 case 'rack': body=msg(j?`Für „${j.name}“ wird ein Rohling aus <strong>${MATERIALS[j.material].name}</strong> benötigt.`:'Nimm zuerst einen Auftrag am Schreibtisch an.')+Object.entries(MATERIALS).map(([id,m])=>`<article class="stock-row"><span class="material-swatch" style="background:${m.color}"></span><div><h3>${m.name}</h3><p>${w.stock[id]} verfügbar</p></div>${action('select-material','Auswählen',id,o?.status!=='accepted'||!w.stock[id])}</article>`).join('')+go('storage','Material nachbestellen');break;
 case 'tools': body=`<h3>Werkzeug für die Drehbank</h3><p>Ausgewählt: <strong>${w.tool==='hss'?'Opas HSS-Meißel':'Hartmetall · Leihwerkzeug'}</strong></p><label class="shop-label">Verschleiß: ${w.wear} %</label><meter value="${w.wear}" min="0" max="100"></meter><div class="tool-options">${action('tool','HSS-Meißel','hss',o?.status==='machining'||w.tool==='hss')}${action('tool','Hartmetall leihen','carbide',o?.status==='machining'||w.tool==='carbide')}</div>${msg('Für den Test stehen beide Werkzeuge bereit. Ab 85 % Verschleiß ist eine Instandsetzung nötig.')}${action('sharpen','Instand setzen · 5 €','',w.wear===0||w.money<5||o?.status==='machining')}`;break;
 case 'cart': body=`<h3>Für den nächsten Arbeitsgang</h3><ul class="shop-list"><li>${o&&o.status!=='accepted'?'✓':'○'} Passender Rohling</li><li>${w.wear<85?'✓':'○'} Schneidwerkzeug einsatzbereit</li><li>✓ Messschieber vorhanden</li></ul>${action('prepare',w.cartReady?'Werkzeuge liegen bereit':'Werkzeuge bereitlegen','',o?.status!=='material')}${go('tools','Werkzeug wechseln')}${go('lathe','Zur Drehbank')}`;break;
 case 'lathe': {
  const running=o?.status==='machining';body=j?`<span class="rubber-stamp">${MATERIALS[j.material].name}</span><h3>${j.name}</h3><div class="part-drawing"><svg viewBox="0 0 260 90" aria-label="Bolzenzeichnung"><path d="M45 25h170v40H45zm0 20h170" stroke="currentColor" fill="none" stroke-width="2"/><path d="M45 76h170m-170-6v12m170-12v12" stroke="currentColor"/><text x="130" y="89" text-anchor="middle">${j.length} mm</text><text x="5" y="15">Ø ${j.diameter} mm</text></svg></div>`:msg('Hier fertigt Opas alte Leitspindeldrehbank deine Teile. Nimm zunächst einen Auftrag an.');
  body+=`<form id="machine-settings"><div class="settings-pair"><label>Drehzahl<select name="rpm" ${running?'disabled':''}>${[300,450,800].map(n=>`<option value="${n}" ${w.settings.rpm===n?'selected':''}>${n} U/min</option>`).join('')}</select></label><label>Vorschub<select name="feed" ${running?'disabled':''}>${[0.1,0.2,0.3].map(n=>`<option value="${n}" ${w.settings.feed===n?'selected':''}>${String(n).replace('.',',')} mm/U</option>`).join('')}</select></label></div><button class="shop-button subtle" type="submit" ${running?'disabled':''}>Schnittwerte übernehmen</button></form>${msg('Testwerte: 450 U/min und 0,1 mm/U ergeben ein maßhaltiges Teil. Andere Einstellungen können Nacharbeit erfordern. Vereinfachte Spielsimulation.')}`;
  if(running)body+=`<div class="machine-progress"><progress id="machine-progress" value="${o.progress}" max="${j.duration}"></progress><p id="machine-progress-label">${Math.floor(o.progress/j.duration*100)} % · ${o.paused?'pausiert':'in Bearbeitung'}</p></div>${action('pause',o.paused?'Bearbeitung fortsetzen':'Bearbeitung pausieren')}`;
  else if(o?.status==='deburred'&&o.measured&&!inTolerance(o))body+=action('rework','Schlichtdurchgang vorbereiten');
  else body+=action('start','Drehbank starten','',o?.status!=='prepared');
  if(o?.status==='machined')body+=go('vise','Teil entgraten');body+=action('light',w.light?'Arbeitslicht ausschalten':'Arbeitslicht einschalten');break;
 }
 case 'vise': body=msg('Spanne das gedrehte Teil ein und entferne die scharfen Kanten.')+action('deburr','Werkstück entgraten','',o?.status!=='machined')+go('measure','Zum Messschieber');break;
 case 'measure': body=j?`<h3>Maßkontrolle</h3><dl class="shop-facts"><div><dt>Sollmaß</dt><dd>Ø ${num(j.diameter)} mm</dd></div><div><dt>Testtoleranz</dt><dd>± 0,10 mm</dd></div><div><dt>Messwert</dt><dd>${o.measured?num(o.actual)+' mm':'Noch nicht gemessen'}</dd></div></dl>${o.measured?`<p class="quality ${inTolerance(o)?'passed':'failed'}">${inTolerance(o)?'✓ Maßhaltig':'Nacharbeit erforderlich'}</p>`:''}${action('measure','Durchmesser messen','',o.status!=='deburred')}${o.status==='checked'?go('desk','Auftrag abgeben'):o.measured?go('lathe','Teil nacharbeiten'):''}`:msg('Erst nach dem Drehen und Entgraten wird der Durchmesser geprüft.');break;
 case 'clean': body=`<h3>Ordnung gehört dazu.</h3><dl class="shop-facts"><div><dt>Am Boden</dt><dd>${w.chips} Portionen Späne</dd></div><div><dt>Im Eimer</dt><dd>${w.scrap} Portionen</dd></div></dl>${action('clean','Späne zusammenkehren','',!w.chips)}${action('sell-scrap','Schrott verkaufen · '+euro(w.scrap*3),'',!w.scrap)}${msg('Nach fünf Durchgängen muss der Arbeitsplatz gereinigt werden.')}`;break;
 case 'radio': body=`<h3>Opas Radio</h3>${msg('Ein leiser, eigens erzeugter Werkstattklang. Die Wiedergabe startet erst mit deinem Antippen.')}${action('radio',w.radio?'Radio ausschalten':'Radio einschalten')}<label class="shop-label" for="radio-volume">Lautstärke: ${w.volume} %</label><input id="radio-volume" type="range" min="0" max="100" value="${w.volume}"><p class="shop-note" id="audio-state">${w.radio?'Radio eingeschaltet.':'Radio ausgeschaltet.'}</p>`;break;
 case 'cat': body=`<h3>Späne</h3>${msg('Opa hat nicht nur seine Werkzeuge hiergelassen. Späne behält ihren Lieblingsplatz neben der Drehbank.')}${action('pet','Späne streicheln')}<p class="shop-note">${w.catPets?`${w.catPets} Mal gestreichelt. Ein zufriedenes Schnurren.`:'Sie schläft noch.'}</p>`;break;
 case 'build': body=`<h3>Die Werkstatt wächst.</h3><p>${w.room.width} × ${w.room.depth} m · ${w.room.width*w.room.depth} m²</p><article class="job-card"><h3>Erster Anbau</h3><p>Ein zusätzlicher Bereich für neue Maschinen.</p>${action('extend',w.room.extension?'Anbau vorhanden':'Um 10 m² erweitern · 200 €','',w.room.extension||w.money<200)}</article><article class="job-card"><h3>Standbohrmaschine</h3><p>Im Anbau aufstellen und eine Probebohrung ausführen.</p>${action('buy-drill',w.room.drill?'Maschine aufgestellt':'Kaufen & aufstellen · 180 €','',!w.room.extension||w.room.drill||w.money<180)}</article>${msg('Im ersten Test werden Bau und Lieferung sofort abgeschlossen.')}`;break;
 case 'drill':body=`<h3>Neue Standbohrmaschine</h3>${msg('Teste die zusätzliche Maschine mit einer Probebohrung. Dafür wird ein Aluminium-Rohling verbraucht; das Probestück kommt in den Schrott.')}${action('drill-test','Probebohrung · 1 Alu-Rohling','',!w.room.drill||!w.stock.aluminium)}`;break;
 default:body=instruction(w);
 }
 return `<div class="station-heading"><div><span>ARBEITSBEREICH</span><h2>${STATIONS[selected]||'Werkstatt'}</h2></div><button class="close-station" data-close-station aria-label="Arbeitsbereich schließen">×</button></div><div class="station-body">${body}</div>`;
}
export function workshopHTML(w,name,selected,tab='new',zoom=1){
 const next=nextTask(w),o=activeOrder(w);
 return `<div class="shop-topbar"><div class="shop-name"><span>TURNING POINT</span><h1>${esc(name)}</h1></div><div class="shop-wallet">${euro(w.money)}<small>WERKSTATTKASSE</small></div><button class="shop-menu-button" data-open-menu>☰ <span>Menü</span></button></div>
 <div class="shop-stage ${selected?'has-station':''}"><section class="scene-area" aria-label="Deine Werkstatt"><div class="scene-topline"><span>OPAS WERKSTATT · ${w.room.width*w.room.depth} m²</span><span class="machine-status" id="scene-machine-status">${o?.status==='machining'?(o.paused?'MASCHINE PAUSIERT':'DREHBANK LÄUFT'):'BEREIT'}</span></div><div class="scene-scroll"><div class="scene-canvas" style="width:${zoom*100}%;min-width:${zoom*100}%">${renderScene(w,selected)}</div></div><div class="scene-controls"><button data-zoom="out" aria-label="Werkstatt verkleinern" ${zoom<=1?'disabled':''}>−</button><button data-zoom="reset">Übersicht</button><button data-zoom="in" aria-label="Werkstatt vergrößern" ${zoom>=2?'disabled':''}>+</button></div><div class="task-strip"><span>›</span><p>${next.text}</p><button data-station="${next.station}">Öffnen</button></div></section>
 <aside class="station-sheet" ${selected?'':'hidden'} aria-label="Arbeitsbereich">${selected?stationPanel(w,selected,tab):''}</aside></div>
 <nav class="station-nav" aria-label="Arbeitsbereiche">${Object.entries(STATIONS).filter(([id])=>id!=='drill'||w.room.drill).map(([id,label])=>`<button data-station="${id}" ${selected===id?'aria-current="true"':''}>${label.split(' · ')[0]}</button>`).join('')}</nav><div class="shop-save-line" id="shop-save-state">Fortschritt wird nach jeder Aktion automatisch gespeichert.</div>`;
}
