import { qualityReport, rewardFor, CUTTERS } from './machining.js?v=007';
import { latheControls } from './lathe-ui.js?v=007';
import { JOBS, MATERIALS, activeOrder, jobFor, nextTask, inTolerance } from './workshop-state.js?v=007';
import { SCENE_DEFS, ROOM_SHELL, OBJECT_ART } from './scene.js?v=007';
export const STATIONS={desk:'Schreibtisch · Aufträge',storage:'Regal · Lager',lathe:'Drehbank',tools:'Werkzeugschrank',rack:'Materialständer',cart:'Werkzeugwagen',vise:'Schraubstock',measure:'Messschieber',radio:'Radio',clean:'Späneeimer & Besen',build:'Bauplan · Ausbau',cat:'Späne',drill:'Standbohrmaschine'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const num=n=>n.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
const go=(id,label)=>`<button class="shop-button subtle" data-station="${id}">${label} →</button>`;
const action=(id,label,arg='',disabled=false)=>`<button class="shop-button" data-work="${id}" data-arg="${arg}" ${disabled?'disabled':''}>${label}</button>`;
const msg=t=>`<p class="shop-note">${t}</p>`;
function instruction(w){const next=nextTask(w);return `<div class="next-step"><span>NÄCHSTER SCHRITT</span><p>${next.text}</p>${go(next.station,'Dorthin')}</div>`;}
export function renderScene(w,selected){
 const hint=nextTask(w).station;
 const deskY=w.room.layout.find(p=>p.id==='desk').y;
 const layer=p=>p.id==='measure'||p.id==='vise'?deskY+1:p.y;
 const objects=[...w.room.layout].sort((a,b)=>layer(a)-layer(b)).map(p=>`<g class="scene-object ${p.id===selected?'selected':''} ${p.id===hint?'next-object':''}" data-station="${p.id}" role="button" tabindex="0" aria-label="${esc(STATIONS[p.id])}" transform="translate(${p.x} ${p.y})"><title>${esc(STATIONS[p.id])}</title>${OBJECT_ART[p.id]}<g class="object-pin"><circle cy="18" r="10"/><text y="23" text-anchor="middle">${p.id===hint?'!':'+'}</text></g></g>`).join('');
 const extension=w.room.extension?`<g class="extension"><path d="M925 830l235-136v125l-155 90z" fill="#a3a28b" stroke="#4e604e" stroke-width="5"/><path d="M930 820l150-87m-95 128 156-89" stroke="#788474" stroke-width="2"/><text x="1015" y="842" fill="#364d3c" font-size="14" transform="rotate(-30 1015 842)">ANBAU · +10 m²</text>${w.room.drill?`<g data-station="drill" class="scene-object" role="button" tabindex="0" aria-label="Standbohrmaschine" transform="translate(1085 792)"><title>Standbohrmaschine</title><path d="M-45 0l45 23 34-21-45-23z" fill="#687e61" stroke="#2b4033" stroke-width="3"/><path d="M0 2v-125" stroke="#a8b1a4" stroke-width="13"/><path d="M-31-65l48 22 25-14-45-23z" fill="#5f7c56"/><path d="M-28-152h60v40h-60z" fill="#537a51" stroke="#2b4033" stroke-width="3"/><path d="M-17-112v39m48-56 27 22" stroke="#bec4ae" stroke-width="5"/><circle cx="60" cy="-105" r="5" fill="#273d2e"/></g>`:''}</g>`:'';
 let chips='';for(let i=0;i<w.chips*7;i++)chips+=`<rect x="${510+(i*37)%185}" y="${573+(i*17)%50}" width="5" height="2" fill="#bdc5ab"/>`;
 return `<svg class="room-svg ${w.light?'':'dimmed'} ${activeOrder(w)?.status==='machining'&&!activeOrder(w)?.paused?'machine-running':''}" viewBox="0 0 1220 940" xmlns="http://www.w3.org/2000/svg" aria-label="Isometrische Werkstatt. Die Einrichtungsgegenstände sind anklickbar.">${SCENE_DEFS}${ROOM_SHELL}<g>${chips}</g>${objects}${extension}</svg>`;
}
export function stationPanel(w,selected,tab='new'){
 const o=activeOrder(w),j=jobFor(o);let body='';
 switch(selected){
 case 'desk': {
  const tabs=[['new','Neu'],['active','In Arbeit'],['done','Abgeschlossen']];
  body=`<div class="order-tabs" role="tablist" aria-label="Aufträge">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" data-order-tab="${id}">${label}</button>`).join('')}</div>`;
  const rows=w.orders.filter(x=>tab==='new'?x.status==='new':tab==='done'?x.status==='completed':!['new','completed'].includes(x.status));
  body+=rows.length?rows.map(x=>{const job=jobFor(x);return `<article class="job-card"><span class="rubber-stamp">${tab==='done'?'ERLEDIGT':'AUFTRAG'}</span><h3>${job.name}</h3><p>${job.detail}</p><dl class="shop-facts"><div><dt>Kunde</dt><dd>${job.customer}</dd></div><div><dt>Zeichnung</dt><dd>Ø ${job.diameter} × ${job.length} mm</dd></div><div><dt>Werkstoff</dt><dd>${MATERIALS[job.material].name}</dd></div><div><dt>Qualität</dt><dd>Ø ± 0,10 mm · L ± 0,20 mm · Ra ≤ 3,20 µm</dd></div><div><dt>${tab==='done'?'Ausgezahlt':'Grundlohn + Genauigkeit'}</dt><dd>${tab==='done'?euro(x.payout):euro(job.pay)+' bis '+euro(Math.round(job.pay*1.5))}</dd></div></dl>${tab==='new'?action('accept','Auftrag annehmen',job.id,!!o):tab==='done'?msg('Geprüft, übergeben und bezahlt: '+euro(x.payout)+'.'):x.status==='checked'?action('deliver','Abgeben · '+euro(rewardFor(x,job).total)):instruction(w)}</article>`;}).join(''):msg(tab==='new'?'Alle angebotenen Testaufträge sind angenommen oder erledigt.':tab==='done'?'Hier erscheinen deine fertig abgelieferten Aufträge.':'Momentan ist kein Auftrag in Bearbeitung.');
  if(o&&tab==='new')body+=go('desk','Laufenden Auftrag ansehen');break;
 }
 case 'storage': body=msg('Rohmaterial und fertige Teile. Lieferungen kommen im Funktionstest sofort an.')+Object.entries(MATERIALS).map(([id,m])=>`<article class="stock-row"><span class="material-swatch" style="background:${m.color}"></span><div><h3>${m.name}</h3><p>${w.stock[id]} Rohlinge · ${euro(m.price)} / Stück</p></div>${action('buy-material','+3 · '+euro(m.price*3),id,w.money<m.price*3)}</article>`).join('')+`<div class="shop-divider">FERTIGE TEILE</div>`+msg(w.orders.filter(x=>['deburred','checked'].includes(x.status)).map(x=>jobFor(x).name+(x.status==='checked'?' · geprüft':' · Prüfung offen')).join('<br>')||'Noch keine fertigen Teile im Lager.');break;
 case 'rack': body=msg(j?`Für „${j.name}“ wird ein Rohling aus <strong>${MATERIALS[j.material].name}</strong> benötigt.`:'Nimm zuerst einen Auftrag am Schreibtisch an.')+Object.entries(MATERIALS).map(([id,m])=>`<article class="stock-row"><span class="material-swatch" style="background:${m.color}"></span><div><h3>${m.name}</h3><p>${w.stock[id]} verfügbar</p></div>${action('select-material','Auswählen',id,o?.status!=='accepted'||!w.stock[id])}</article>`).join('')+go('storage','Material nachbestellen');break;
 case 'tools': body=Object.entries(CUTTERS).map(([id,c])=>`<article class="job-card"><h3>${c.name}</h3><p>${c.detail}</p>${action('cutter',w.cutter===id?'Eingesetzt':'Einsetzen',id,w.cutter===id||(o?.status==='machining'&&!o.paused))}</article>`).join('')+`<h3>Werkzeug für die Drehbank</h3><p>Ausgewählt: <strong>${w.tool==='hss'?'Opas HSS-Meißel':'Hartmetall-Meißel'}</strong></p><label class="shop-label">Verschleiß: ${num(w.wear)} %</label><meter value="${w.wear}" min="0" max="100"></meter><div class="tool-options">${action('tool','HSS-Meißel','hss',(o?.status==='machining'&&!o.paused)||w.tool==='hss')}${action('tool','Hartmetall · 12 €','carbide',(o?.status==='machining'&&!o.paused)||w.tool==='carbide')}</div>${msg('HSS: niedrige Schnittgeschwindigkeit. Hartmetall: höhere Geschwindigkeit, weniger Verschleiß; Wechsel 12 €. Ab 85 % Verschleiß vor dem nächsten Einspannen instand setzen.')}${action('sharpen','Instand setzen · 5 €','',w.wear===0||w.money<5||(o?.status==='machining'&&!o.paused))}`;break;
 case 'cart': body=`<h3>Für den nächsten Arbeitsgang</h3><ul class="shop-list"><li>${o&&o.status!=='accepted'?'✓':'○'} Passender Rohling</li><li>${w.wear<85?'✓':'○'} Schneidwerkzeug einsatzbereit</li><li>✓ Messschieber vorhanden</li></ul>${action('prepare',w.cartReady?'Werkzeuge liegen bereit':'Werkzeuge bereitlegen','',o?.status!=='material')}${go('tools','Werkzeug wechseln')}${go('lathe','Zur Drehbank')}`;break;
 case 'lathe': body=latheControls(w,o,j);break;
 case 'vise': body=msg('Spanne das gedrehte Teil ein und entferne die scharfen Kanten.')+action('deburr','Werkstück entgraten','',o?.status!=='machined')+go('measure','Zum Messschieber');break;
 case 'measure': {
  const q=o?.piece?qualityReport(o,j):null;
  body=j?`<h3>Werkstückprüfung</h3><dl class="shop-facts"><div><dt>Prüfumfang</dt><dd>Profil, Oberfläche, Werkstoff</dd></div>${o.measured&&q?`<div><dt>Ø min / max</dt><dd>${num(q.min)} / ${num(q.max)} mm</dd></div><div><dt>Länge min / max</dt><dd>${num(q.minLength)} / ${num(q.length)} mm</dd></div><div><dt>Ra · Mantel und Stirnfläche</dt><dd>${num(q.roughness)} µm</dd></div>`:''}</dl>${o.measured&&q?`<p class="quality ${q.ok?'passed':'failed'}">${q.ok?'✓ Maß, Oberfläche und Werkstoff stimmen.':q.reasons.join(' ')}</p>`:''}${action('measure','Profil und Oberfläche prüfen','',o.status!=='deburred')}${o.status==='checked'?msg('Grundlohn '+euro(j.pay)+' + Genauigkeitsbonus '+euro(rewardFor(o,j).bonus)+' = '+euro(rewardFor(o,j).total))+go('desk','Auftrag abgeben'):o.measured?go('lathe','Nacharbeiten oder Rohling ersetzen'):''}`:msg('Drehe und entgrate zuerst ein Werkstück.');break;
 }
 case 'clean': body=`<h3>Ordnung gehört dazu.</h3><dl class="shop-facts"><div><dt>Am Boden</dt><dd>${w.chips} Portionen Späne</dd></div><div><dt>Im Eimer</dt><dd>${w.scrap} Portionen</dd></div></dl>${action('clean','Späne zusammenkehren','',!w.chips)}${action('sell-scrap','Schrott verkaufen · '+euro(w.scrap*3),'',!w.scrap)}${msg('Nach fünf Durchgängen muss der Arbeitsplatz gereinigt werden.')}`;break;
 case 'radio': body=`<h3>Opas Radio</h3>${msg('Ein leiser, eigens erzeugter Werkstattklang. Die Wiedergabe startet erst mit deinem Antippen.')}${action('radio',w.radio?'Radio ausschalten':'Radio einschalten')}<label class="shop-label" for="radio-volume">Lautstärke: ${w.volume} %</label><input id="radio-volume" type="range" min="0" max="100" value="${w.volume}"><p class="shop-note" id="audio-state">${w.radio?'Radio eingeschaltet.':'Radio ausgeschaltet.'}</p>`;break;
 case 'cat': body=`<h3>Späne</h3>${msg('Opa hat nicht nur seine Werkzeuge hiergelassen. Späne behält ihren Lieblingsplatz neben der Drehbank.')}${action('pet','Späne streicheln')}<p class="shop-note">${w.catPets?`${w.catPets} Mal gestreichelt. Ein zufriedenes Schnurren.`:'Sie schläft noch.'}</p>`;break;
 case 'build': body=`<h3>Die Werkstatt wächst.</h3><p>${w.room.width} × ${w.room.depth} m · ${w.room.width*w.room.depth} m²</p><article class="job-card"><h3>Erster Anbau</h3><p>Ein zusätzlicher Bereich für neue Maschinen.</p>${action('extend',w.room.extension?'Anbau vorhanden':'Um 10 m² erweitern · 200 €','',w.room.extension||w.money<200)}</article><article class="job-card"><h3>Standbohrmaschine</h3><p>Im Anbau aufstellen und eine Probebohrung ausführen.</p>${action('buy-drill',w.room.drill?'Maschine aufgestellt':'Kaufen & aufstellen · 180 €','',!w.room.extension||w.room.drill||w.money<180)}</article>${msg('Im ersten Test werden Bau und Lieferung sofort abgeschlossen.')}`;break;
 case 'drill':body=`<h3>Neue Standbohrmaschine</h3>${msg('Teste die zusätzliche Maschine mit einer Probebohrung. Dafür wird ein Aluminium-Rohling verbraucht; das Probestück kommt in den Schrott.')}${action('drill-test','Probebohrung · 1 Alu-Rohling','',!w.room.drill||!w.stock.aluminium)}`;break;
 default:body=instruction(w);
 }
 return `<div class="station-heading"><div><span>ARBEITSBEREICH</span><h2>${STATIONS[selected]||'Werkstatt'}</h2></div><button class="close-station" data-close-station aria-label="Arbeitsbereich schließen">×</button></div><div class="station-body">${body}</div>`;
}
export function workshopHTML(w,name,selected,tab='new',zoom=1){
 const next=nextTask(w),o=activeOrder(w);
 return `<div class="shop-topbar"><div class="shop-name"><span>TURNING POINT</span><h1>${esc(name)}</h1></div><div class="shop-wallet">${euro(w.money)}<small>WERKSTATTKASSE</small></div><button class="shop-menu-button" data-open-menu>☰ <span>Menü</span></button></div>
 <div class="shop-stage ${selected==='lathe'?'lathe-focus':''} ${selected?'has-station':''}"><section class="scene-area" aria-label="Deine Werkstatt"><div class="scene-topline"><span>OPAS WERKSTATT · ${w.room.width*w.room.depth} m²</span><span class="machine-status" id="scene-machine-status">${o?.status==='machining'?(o.paused?'MASCHINE PAUSIERT':'DREHBANK LÄUFT'):'BEREIT'}</span></div><div class="scene-scroll"><div class="scene-canvas" style="width:${zoom*100}%;min-width:${zoom*100}%">${renderScene(w,selected)}</div></div><div class="scene-controls"><button data-zoom="out" aria-label="Werkstatt verkleinern" ${zoom<=1?'disabled':''}>−</button><button data-zoom="reset">Übersicht</button><button data-zoom="in" aria-label="Werkstatt vergrößern" ${zoom>=2?'disabled':''}>+</button></div><div class="task-strip"><span>›</span><p>${next.text}</p><button data-station="${next.station}">Öffnen</button></div></section>
 <aside class="station-sheet" ${selected?'':'hidden'} aria-label="Arbeitsbereich">${selected?stationPanel(w,selected,tab):''}</aside></div>
 <nav class="station-nav" aria-label="Arbeitsbereiche">${Object.entries(STATIONS).filter(([id])=>id!=='drill'||w.room.drill).map(([id,label])=>`<button data-station="${id}" ${selected===id?'aria-current="true"':''}>${label.split(' · ')[0]}</button>`).join('')}</nav><div class="shop-save-line" id="shop-save-state">Fortschritt wird nach jeder Aktion automatisch gespeichert.</div>`;
}
